version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: barber
      POSTGRES_PASSWORD: barberpass
      POSTGRES_DB: barbearia
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U barber"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://barber:barberpass@db:5432/barbearia
      SECRET_KEY: supersecretkeychange
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: "120"
      CORS_ORIGINS: http://localhost:5173,http://frontend:5173
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    ports:
      - "5173:5173"

volumes:
  db_data: